image:
  repository: ghcr.io/onedr0p/qbittorrent
  pullPolicy: IfNotPresent
  tag: 4.6.3@sha256:a4ad890e8c4a287c17d12ca22eb1d84a046aba2efbd882bf7d6eb12459f6a70c
qbitportforwardImage:
  repository: mjmeli/qbittorrent-port-forward-gluetun-server
  pullPolicy: IfNotPresent
  tag: latest@sha256:67d0d21ed792cf80716d4211e7162b6d375af5c12f3cf096c9032ad705dddaa8
exportarrImage:
  repository: ghcr.io/esanchezm/prometheus-qbittorrent-exporter
  pullPolicy: IfNotPresent
  tag: v1.5.1@sha256:3aef59197a9f14fc36a9963848d495f9a85e4f096b448a0ed4cb3aca122e793b 
qbitportforward:
  enabled: false
  QBT_USERNAME: "admin"
  QBT_PASSWORD: "adminadmin"
service:
  main:
    ports:
      main:
        port: 10095
        targetPort: 8080
  torrent:
    enabled: true
    ports:
      torrent:
        enabled: true
        port: 6881
        protocol: tcp
      torrentudp:
        enabled: true
        port: "{{ .Values.service.torrent.ports.torrent.port }}"
        protocol: udp
  gluetun:
    enabled: true
    type: ClusterIP
    ports:
      gluetun:
        enabled: true
        port: 8000
        targetPort: 8000
        protocol: http
  metrics:
    enabled: true
    type: ClusterIP
    targetSelector: exportarr
    ports:
      metrics:
        enabled: true
        port: 8000
        targetSelector: exportarr
workload:
  qbitportforward:
    enabled: true
    type: Deployment
    strategy: RollingUpdate
    replicas: 1
    podSpec:
      containers:
        qbitportforward:
          primary: true
          enabled: true
          imageSelector: qbitportforwardImage
          probes:
            liveness:
              enabled: false
            readiness:
              enabled: false
            startup:
              enabled: false
          env:
            QBT_USERNAME: "{{ .Values.qbitportforward.QBT_USERNAME }}"
            QBT_PASSWORD: "{{ .Values.qbitportforward.QBT_PASSWORD }}"
            QBT_ADDR: '{{ printf "http://%v:%v" (include "tc.v1.common.lib.chart.names.fullname" $) .Values.service.main.ports.main.port }}'
            GTN_ADDR: '{{ printf "http://%v-gluetun:8000" (include "tc.v1.common.lib.chart.names.fullname" $) }}'
exportarr:
    enabled: true
    type: Deployment
    strategy: RollingUpdate
    replicas: 1
    podSpec:
      containers:
        exportarr:
          primary: true
          enabled: true
          imageSelector: exportarrImage
          args:
            - qbittorrent-exporter
          probes:
            liveness:
              enabled: false
            readiness:
              enabled: false
            startup:
              enabled: false
          env:
            INTERFACE: 0.0.0.0
            EXPORTER_PORT: "{{ .Values.service.metrics.ports.metrics.port }}"
            QBITTORRENT_HOST: '{{ printf "http://%v" (include "tc.v1.common.lib.chart.names.fullname" ) }}'
            QBITTORRENT_PORT: "{{ .Values.service.main.ports.main.port }}"
            QBT_USERNAME: "{{ .Values.qbitportforward.QBT_USERNAME }}"
            QBT_PASSWORD: "{{ .Values.qbitportforward.QBT_PASSWORD }}"
            ENABLE_ADDITIONAL_METRICS: false
            ENABLE_UNKNOWN_QUEUE_ITEMS: false
persistence:
  config:
    enabled: true
    mountPath: "/config"
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
